spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8891/oauth2/jwks"