server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amit---kumar/config-store
          default-label : main
          searchPaths:
            - service/sb3/notification-service*
            - service/sb3/search-service*
            - service/sb3/eureka-service*
            - service/sb3/oauth-service*
            - service/sb3/gateway-service*